name: CI Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # You can specify the version you need
    
    - name: Install dependencies
      run: npm install

    - name: Lint TypeScript code
      run: npm run lint  # Make sure you have linting script defined in package.json

    - name: Run unit tests
      run: npm test  # Ensure you have test script in package.json

    - name: Build the TypeScript application
      run: npm run build  # Ensure you have build script in package.json

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/urban-mobility-smart-transportation:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/urban-mobility-smart-transportation:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
